### ISSUE TITLE
rez-context broken for FileSystemCombinedPackageResource

### ISSUE THREAD

**Issue by elrond79** [nerdvegas/rez#162]
If you try to call rez-context when a FileSystemCombinedPackageResource is active, you get a traceback:

```
Traceback (most recent call last):
  File "/Volumes/sv-dev01/devRepo/paulm/rez-src/bin/rez-context", line 3, in <module>
    run("context")
  File "/Volumes/sv-dev01/devRepo/paulm/rez-src/src/rez/cli/_main.py", line 107, in run
    returncode = opts.func(opts, opts.parser, arg_groups[1:])
  File "/Volumes/sv-dev01/devRepo/paulm/rez-src/src/rez/cli/context.py", line 134, in command
    rc.print_info(verbosity=opts.verbose)
  File "/Volumes/sv-dev01/devRepo/paulm/rez-src/src/rez/resolved_context.py", line 645, in print_info
    if not os.path.exists(pkg.root):
  File "/usr/local/python-2.7.4/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

The immediate issue is that Combined resources have a root of "None" - so, if this is an allowed value, we need to check for this before feeding into pkg.root.

The larger issue, though, is that there's no clear / consistent way of answering the question, "Where did this package come from?" (or where is it installed) for all packages.

**Comment by nerdvegas** [comment]
Closing this issue as it is addressed in resources2 branch.

There, packages/variants have a 'uri' property that does describe where the package comes from, whether that be a file or something else (potentially a database, with future additions of new package repository types).

**Comment by elrond79** [comment]
Hmm... actually, this bug report was FOR the resources2 branch. I pulled the latest, and checked, and it's still present:

```
Traceback (most recent call last):
  File "/Volumes/sv-dev01/devRepo/paulm/rez-src/bin/rez-context", line 3, in <module>
    run("context")
  File "/Volumes/sv-dev01/devRepo/paulm/rez-src/src/rez/cli/_main.py", line 107, in run
    returncode = opts.func(opts, opts.parser, arg_groups[1:])
  File "/Volumes/sv-dev01/devRepo/paulm/rez-src/src/rez/cli/context.py", line 139, in command
    source_order=opts.source_order)
  File "/Volumes/sv-dev01/devRepo/paulm/rez-src/src/rez/resolved_context.py", line 656, in print_info
    if not os.path.exists(pkg.root):
  File "/usr/lib64/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by nerdvegas** [comment]
Ah right you are - I'll sort this next week.
A

**Comment by elrond79** [comment]
Made this pull request as a potential fix for this issue:

https://github.com/nerdvegas/rez/pull/172

However, it's not an ideal solution - read the comment for thoughts / possible alternative ideas.
